use_frameworks!

target 'SatelliteIOS_Example' do
  pod 'SatelliteIOS', :path => '../'

  target 'SatelliteIOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
